name: tests
on:
  push:
    branches: ['*']
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Downgrade pip
        run: python -m pip install pip==23.3.2
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run doctests
        run: python -m doctest -v docchat.py
